/*
 * miio_instance_version.h
 *
 *  Created on: Oct 30, 2018
 *      Author: mashaoze
 */
#ifndef _MIIO_INSTANCE_VERSION_H_
#define _MIIO_INSTANCE_VERSION_H_

#include "miio_version.h"

#define MIIO_INSTANCE_VERSION_MAJOR		2
#define MIIO_INSTANCE_VERSION_MINOR		2
#define MIIO_INSTANCE_VERSION_PATCH		4
#define MIIO_INSTANCE_VERSION_STR		MIIO_POINT_VERSION_STR(MIIO_INSTANCE_VERSION_MAJOR, MIIO_INSTANCE_VERSION_MINOR, MIIO_INSTANCE_VERSION_PATCH)

#endif
